apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Chart.Name }}-ollama"
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{ $.Chart.Name }}-ollama"
  template:
    metadata:
      labels:
        app: "{{ $.Chart.Name }}-ollama"
    spec:
      containers:
        - name: "{{ $.Chart.Name }}-ollama"
          image: ollama/ollama:0.15.6
          ports:
            - containerPort: 11434
          resources:
            limits: {}
          volumeMounts:
            - name: "{{ $.Chart.Name }}-ollama-storage"
              mountPath: /root/.ollama
      volumes:
        - name: "{{ $.Chart.Name }}-ollama-storage"
          persistentVolumeClaim:
            claimName: "{{ $.Chart.Name }}-ollama-pvc"
