{{- if and (or (eq .Values.services.app.environment "production") (eq .Values.services.app.environment "mainnet")) .Values.services.nocodb.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $.Chart.Name }}-nocodb-ingress-route"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}-nocodb
    app.kubernetes.io/instance: {{ .Values.namespace }}
    app.kubernetes.io/component: database-ui
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
    - websecure
    - websecure-udp
  tls:
    secretName: wildcard-catalystexplorer-ssl
  routes:
    - match: Host(`dataset.catalystexplorer.com`)
      kind: Rule
      priority: 10
      middlewares:
        - name: traefik-redirect-http-to-https@kubernetescrd
          namespace: traefik
        - name: traefik-default-headers@kubernetescrd
          namespace: traefik
        - name: traefik-traefik-http3-headers@kubernetescrd
          namespace: traefik
      services:
        - name: "{{ $.Chart.Name }}-nocodb-service"
          namespace: {{ .Values.namespace }}
          port: 8080
{{- end -}}