apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Chart.Name }}-secrets"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{ range .Files.Lines "app_env" }}
  {{   if . }}
  {{     $parts := regexSplit "=" . 2 }}
  {{     index $parts 0  }}: {{ index $parts 1 | b64enc }}
  {{   end }}
  {{ end }}